title: LI Consulting
description: LI consulting is a data analytics and consultating firm
logo: /assets/img/logo_full_grey.png
show_downloads: true
google_analytics: G-PJYVERGYT3
theme: jekyll-theme-minimal
