title: LI consulting
description: Provides business data analytics and consultation. Extract maximum value from your assets.
logo: /assets/img/logo_full_grey.png
show_downloads: true
google_analytics: G-PJYVERGYT3
theme: jekyll-theme-minimal
