title: LI Consulting GitHub
logo: /assets/img/logo_full_grey.png
description: LI Consulting provides business data analytics and consultation.
google_analytics: G-PJYVERGYT3
theme: jekyll-theme-minimal
