title: LI consulting
description: A firm that provides business data analytics and consultation. Extract maximum value from your assets.
logo: /assets/img/logo_full_grey.png
show_downloads: false
google_analytics: G-PJYVERGYT3
theme: jekyll-theme-minimal
