title: LI Consulting GitHub
description: A family-run firm that provides business data analytics and consultation. Extract maximum value from your assets.
google_analytics: G-PJYVERGYT3
theme: jekyll-theme-minimal
